### ISSUE TITLE
Skip postcss-calc if IE > 9

### ISSUE THREAD

**Issue by silvenon** [MoOx/postcss-cssnext#188]
[postcss-calc](https://github.com/postcss/postcss-calc) is an optimization plugin, it doesn't allow you to use `calc()`, it just saves you from using it too much.

**Comment by MoOx** [comment]
I know what provide postcss-calc since I wrote this plugin.
In order to provide the best browser support for, let's say, var(), it makes sense to provide this optimization so a value `calc(var(--fontSize) * 2)` can be directly reduced to a value that works even in IE 8.

That said, it will be nice to disable this feature if IE in the scope is > 9. Related to #164

**Comment by MoOx** [comment]
Also please keep in mind all the following known issues http://caniuse.com/#search=calc so not sure if it make sense to disable this plugin for now...

You can still disable it by using the following option:

```js
{
  features: {
    calc: false
  }
}
```

**Comment by silvenon** [comment]
Oh, I see! I didn't see it as a fallback, my bad :sweat_smile:

**Comment by renestalder** [comment]
I'm quite happy how CSS PostCSS-calc works by default because of the known issues with multiplication and division.

**Comment by MoOx** [comment]
Yeah it would be interesting to keep this enabled for browsers that have know issues.
@renestalder any data to provide?

**Comment by renestalder** [comment]
I don't have more specific data since I rely to the links on Can I Use.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
