### ISSUE TITLE
Should custom properties be ignored when not scoped to :root?

### ISSUE THREAD

**Issue by davidmaxwaterman** [MoOx/postcss-cssnext#246]
I tried to declare some custom properties inside a css rule, something like this :

```
my-circle {
  --radius: 50;
  width: var(--radius)px;
  height: var(--radius)px;

  background-size: var(--radius)px var(--radius)px;
}
```

but I get the error message about the variable not being scoped to :root, and was forced to put them into the global scope, when I really didn't need to.

I looked in the spec, and it seemed to imply that I could do what I want, so I was wondering why cssnext isn't allowing it. Any ideas?

**Comment by topaxi** [comment]
It's impossible to transpile for older browsers. All the transpiling process basically does is string replacement, while more complex custom properties need scoping and cascading.

Because of this, it is limited to `:root` only, this way the basic string replacement works across all browsers. 

Checkout http://philipwalton.com/articles/why-im-excited-about-native-css-variables/#the-limitations-of-preprocessor-variables for how this is going to be more powerful than normal pre/post-processing, and why it's impossible to transpile (It might be possible with a JavaScript runtime though).

**Comment by davidmaxwaterman** [comment]
I don't quite get your point.

I'm just interested in a variable being local to the css rule it is declared in. It should be trivial to just replace the value inside that rule, and it has no effect outside. As it is, I have to move it to a :root rule and prefix it to give it some scope. It's true that I have to do that if I want to use that variable in other rules, but that's not what I want to do here.

Am I missing something?

**Comment by topaxi** [comment]
The point is, it won't be compatible with an actual CSS feature, which for example landed in Chrome Canary and Firefox (don't remember the version, quite a while now..).
The problem is, if you declare the variable in a rule, it won't be local to this rule but all descendant rules too.

cssnext tries to be compatible with future CSS standards so it can't break the actual standard.

It might be possible to do what you try to achieve, but this should be solved in a different / new module then.

**Comment by davidmaxwaterman** [comment]
yes, that makes sense.

thanks.
