### ISSUE TITLE
Duplicate autoprefixer

### ISSUE THREAD

**Issue by Zougi** [MoOx/postcss-cssnext#271]
Hello,
I just opened an issue on https://github.com/postcss/gulp-postcss/issues/76
Is it normal postcss-cssnext is shipped with autoprefixer? this same package is already a postcss plugin.
Thanks

**Comment by MoOx** [comment]
(postcss-)cssnext is a plugin to allow you to write future proof css. autoprefixer is one of many features included in this plugin (that is just a collection of plugin).
gulp-postcss doc (like 99% of all postcss tutorial) is totally wrong. cssnext include autoprefixer since the beginning as well as many postcss plugins I wrote in the first place (even if I rip many from rework equivalent but that's not the point).

Also note that autoprefixer should be a plugin called at the bottom of your plugin list, otherwise, it won't prefixes rules generated by other plugins called after.

**Comment by MoOx** [comment]
FYI https://github.com/postcss/gulp-postcss/pull/77

**Comment by Zougi** [comment]
Thx for the clarification MoOx

**Comment by ShaggyDude** [comment]
Where is the list of plugins inside of cssnext?
Thanks,

**Comment by daemth** [comment]
When using cssnext, do you still have to include all the seperate plugins or are they all includes in the cssnext-package?
Thanks!

**Comment by MoOx** [comment]
Did you even read the homepage http://cssnext.io/ ?
All included features are listed there!

**Comment by daemth** [comment]
What do you think? Ofcourse I did. More than once.
I know that all included features are listed there and as far as I know I don't have to include the listed plugins but I can't get custom properties set and apply to work without including it.

Sorry for bothering, I thought as a developer you'd appreciate honest feedback from a fan of your work. If all the demo's where totally clear I wouldn't have asked.
Kind regards,
Thomas

**Comment by MoOx** [comment]
FYI, cssnext currently automatically enable or disable features depending on your `browsers` scope. So if you say "last 2 chrome", you won't get custom props enable since they are supported by Chrome for a while now (as well as Firefox). 
An other problem you might face is that you will have issue when using custom props in... let's say a color function. This won't work. Cause the color() plugin can't "guess" the custom prop value without any transformation.
So you might need to enable the features by "hand", using a boolean http://cssnext.io/usage/#features

**Comment by daemth** [comment]
Thanks a lot for your feedback! I think this'll help me out :-)
